#pragma once

Console_Variable_Structure Console_Variable_Uber_Alles_Scale;

Console_Variable_Structure Console_Variable_Uber_Alles_Speed;

Console_Variable_Structure Console_Variable_Set_Priority;

Console_Variable_Structure Console_Variable_Get_Priorities;

Console_Variable_Structure Console_Variable_Bruteforce;

Console_Variable_Structure Console_Variable_Bruteforce_Memory;

Console_Variable_Structure Console_Variable_Extrapolation;

Console_Variable_Structure Console_Variable_Extrapolation_Tolerance;

Console_Variable_Structure Console_Variable_Extrapolation_Gravity_Tolerance;

Console_Variable_Structure Console_Variable_Aim_Height;

Console_Variable_Structure Console_Variable_Angle_X;

Console_Variable_Structure Console_Variable_First_Choked_Angle_Y;

Console_Variable_Structure Console_Variable_Second_Choked_Angle_Y;

Console_Variable_Structure Console_Variable_Angle_Y;

Console_Variable_Structure Console_Variable_Minimum_Choked_Commands;

Console_Variable_Structure Console_Variable_Maximum_Choked_Commands;

Console_Variable_Structure Console_Variable_Commentator;